const Map<String, String> enUS = {
  "DELAY": "DELAY",
 "onTime": "On Time",
  "hour": "h",
  "minute": "m",
  "plan": "Plan",
  'return_time': "Return time",
  "phone support": "Phone Support",
  "call 113": "Do you want to call 113?",
  'Unknown': "_____",
  'actual': "Actual",
  'scheduled': "Scheduled",
  'no_information_wallet': "No Information",
  'round_trip': "Round Trip",
  "stopover": "Stopover",
  'Do you want to cancel the trip?': "Do you want to cancel the trip?",
  'save': "Save",
  'Update Name Successfully': "Update Name Successfully",
  'back': "Back",
  'Popular Destinations': "Popular Destinations",
  'morning_greeting': 'Good morning',
  'afternoon_greeting': 'Good afternoon',
  'evening_greeting': 'Good evening',
  'scheduled_time': "Scheduled",
  'passenger': "Passenger",
  'trip_option': "Trip Options",
  'requested': "requested",
  'accepted': "Accepted",
  'in_progress': "In progress",
  'where do you want to go?': "Where do you want to go?",
  'account delete': "Account Delete",
  'change information': "Change Information",
  'change password': "Change Password",
  'current password': "Current Password",
  'confirm password': "Confirm Password",
  "password field do not match !!": "Password Field do not match !!",
  'password change successfully!': "Password change successfully",
  '*required': "*required",
  "new password": "New Password",
  'select vehicle type': "Select Vehicle Type",
  'license_no': "License No",
  'email not valid': "Email Not Valid",
  'full name': "Full Name",
  'Please Enter OTP': "Please Enter OTP",
  'Password change successfully!': "Password change successfully!",
  'Confirm password is invalid': "Confirm password is invalid",
  'Password required at least 6 characters':
      "Password required at least 6 characters",
  'please try again later': "Please try again later",
  'email': "Email",
  'Enter the email address we will send an OTP to create new password.':
      "Enter the email address we will send an OTP to create new password.",
  "signup phone": "Signup Phone",
  'login phone': "Login Phone",
  'sending OTP': " Sending OTP",
  'start': "Start",
  'cash': "Cash",
  'wallet': "Wallet",
  'continue': "Continue",
  'details': " Details",
  'history': "History",
  'airport_sharing': "Airport Sharing",
  'airport_private': "Airport Private",
  'longtrip': "Long Trip",
  'to time': "To time",
  'from time': "From time",
  'Verify OTP': "Verify OTP",
  'Code is Invalid': "Code is Invalid",
  'Trip rejected': "Trip rejected",
  'close': "Close",
  'name': "Name",
  'estimated': "Estimated",
  'trip detail': "Trip Details",
  'completed': "Completed",
  'Failed to load terms of service': "Failed to load terms of service",
  'Failed to load wallet data': "Failed to load wallet data",
  'Failed to load vehicle data': "Failed to load vehicle data",
  'Login failed. Please try again.': "Login failed. Please try again.",
  'Request timed out. Please try again.':
      "Request timed out. Please try again.",
  'No internet connection. Please check your network.'
          'Location permissions are permanently denied, we cannot request permissions.':
      "Location permissions are permanently denied, we cannot request permissions.",
  'Location permissions are denied': "Location permissions are denied",
  'Location services are disabled.': "Location services are disabled.",
  'Failed to load album': "Failed to load album",
  'Something want wrong. Please try again later':
      "Something want wrong. Please try again later",
  'Press Back button again to Exit': "Press Back button again to Exit",
  'no vehicle data': "No Vehicle Data",
  'help via phone': "'Help Via Phone",
  'notification detail': "Notification Detail",
  'no information wallet': "No Information Wallet",
  'please enter name': "Please Enter Name",
  'airport cluster': "Airport Cluster",
  'login successful': "Login Successful!",
  'phone number': "Phone Number",
  'amount': "Amount",
  'status': "Status",
  'return time': "Return time",
  'scheduled time': "Scheduled Time",
  'email or password is incorrect': "Email or password is incorrect",
  'No internet connection. Please check your network.':
      "No internet connection. Please check your network.",
  'Invalid response format from server.':
      "Invalid response format from server.",
  'email already exists': "Email already exists",
  'highlight': "highlights",
  'copy': "Copied",
  'no_data_trip': "No data trip",
  'coming': "Coming",
  'detail': "Detail",
  'hello': "Hello",
  'show_info_fly': "Flight Information",
  'flight_code': "Flight Code",
  'fetch': 'Fetch',
  'no_flight_information_available': 'No flight information available',
  'confirm or change': "Confirm or change your pickup location",
  'confirmed_pickup': "Confirmed Pickup",
  'choose vehicle': "Choose Your Vehicle Type",
  'distance': "Distance",
  'duration': "Duration",
  'select a vehicle': "Please select a vehicle ",
  'payment info': "Payment Info",
  'add stopover': "Add Stopover",
  'payment method': "Payment Method",
  'Please select a Payment method':
      "Please select a Payment method before booking",
  'successfully': "Successfully",
  'from': "From",
  'booking': "Booking",
  'select_service': "Select service",
  'Let’s choose the transport service suitable for you':
      "Let’s choose the transport service suitable",
  'to': "To",
  'airport': "Airport",
  'version': "Version",
  'account': "Account",
  'notification': "Notification",
  'activities': "Activities",
  'please_wait': "Please wait...",
  'delete_account': "Delete account",
  'no': "No",
  'yes': "Yes",
  'Are_you_sure_you_want_to_delete_account?':
      "Are you sure you want to delete account?",
  'help_via_phone': "Help via phone",
  'help_via_email': "Help via email",
  'chang_language': "Language",
  'intro': "Intro",
  'support': "Support",
  'share': "Share",
  'chang_password': "Change Password",
  'are_want_to_logout': "Do you want to logout",
  'Don’t have an account yet?': "Don't have an account yet?",
  'Already have an account?': "Already have an account?",
  'sign_up': "Sign Up",
  'login_with_phone_number': "Login With Phone Number",
  'login_with_email': "Login With Email",
  'app_name': "AirPlan",
  'intro_title_one': "Choose Your Locations",
  'intro_title_two': "Request for Ride",
  'into_dec_one':
      "Passengers can choose their desired location and know the time to reach the destination and the amount they need to pay.",
  'into_dec_two':
      "Passengers can request for a ride easily from anywhere, any time with few steps.",
  'intro_title_three': "Track Your Ride",
  'into_dec_three':
      "Passengers can track their ride and the time required for a cab to arrive and also time to reach the desired destination.",
  'select_profile_photo': "Select a photo for your profile",
  'please_select': "Please Select",
  'gallery': "Gallery",
  'camera': "Camera",
  'select_language': "Select your language",
  'next': "Next",
  'done': "Done",
  'skip': "Skip",
  'enter_information': "Enter \nyour information",
  'phone': "Phone",
  'password': "Password",
  'required': "required",
  'forgot': "Forgot your password?",
  'login': "Login",
  'create': "Create Customer account",
  'address': "Address",
  'confirm_password': "Confirm Password",
  'send': "Send",
  'already_register': "Already Registered,connect",
  'home': "Home",
  'favorite_ride': "Favorite Ride",
  'new_ride': "New",
  'confirmed': "Confirmed",
  'canceled': "Canceled",
  'rent_a_vehicle': "Rent a Vehicle",
  'promo_code': "Promo Code",
  'my_wallet': "My Wallet",
  'change_language': "Change Language",
  'sign_out': "Sign Out",
  'contact_us': "Contact Us",
  'rate_business': "Rate Business",
  'my_profile': "My Profile",
  'delete': "Delete",
  'new': "New",
  'view_path': "View Path",
  'call': "Call",
  'driver': "Driver",
  'conform_your_ride': "Conform your ride",
  'safe_message': "I do not feel safe",
  'sos': "SOS",
  'add_complaint': "Add Complaint",
  'paid': "Paid",
  'book_now': "BOOK NOW",
  'cancel': "Cancel",
  'submit': "Submit",
  'title': "Title",
  'message': "Message",
  'submit_query_message': "Submit your Query",
  'term_policy': "Terms & Policy"
};
