name: customerapp
description: ""
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:

  dio: ^5.4.0
  dartz: ^0.10.0
  http: ^1.2.2
  get: ^4.6.6
  pinput: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_easyloading: ^3.0.5
  google_nav_bar: ^5.0.6
  line_awesome_flutter: ^3.0.1
  flutter_svg: ^2.0.10+1
  flutter_polyline_points: ^2.1.0
  time_picker_spinner_pop_up: ^2.0.0
  flutter_local_notifications: ^17.2.3
  pusher_channels_flutter: ^2.2.1
  intl: ^0.19.0
  pin_code_fields: ^8.0.1
  intl_phone_number_input:
    git:
     url: https://github.com/Shahidbangash/intl_phone_number_input.git
     ref: develop
  uuid: ^4.4.2 # Tạo UUID
  shared_preferences: ^2.2.3
  location:  ^6.0.2
  vietmap_flutter_gl: ^2.2.1
  vietmap_flutter_plugin: ^0.3.0
  url_launcher: ^6.3.0
  flutter_datetime_picker_plus: ^2.2.0
  firebase_core: ^3.4.1
  firebase_messaging: ^15.1.1
  firebase_auth: ^5.3.1

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

dependencies_override:
  dio: ^5.4.0
  dartz: 0.9.10

flutter:
  assets:
    - assets/svg/
    - assets/images/
    - assets/icons/
    - assets/file/
    - assets/flags/
    - assets/

  uses-material-design: true

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 700

flutter_icons:
    android: true
    ios: true
    image_path: "assets/icons/app-icon.png"

